# Generated by Django 5.1.6 on 2025-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0013_producto_codigo_qr"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="costo",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="descuento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
