# Generated by Django 5.1.6 on 2025-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="itbis",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="ITBIS calculado como el 18% del subtotal",
                max_digits=10,
            ),
            preserve_default=False,
        ),
    ]
