# Generated by Django 5.1.6 on 2025-03-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0006_detalleventa_itbis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_referencia", models.CharField(max_length=20)),
                ("banco_emisor", models.CharField(max_length=100)),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferencia",
                        to="ventas.venta",
                    ),
                ),
            ],
        ),
    ]
