# Generated by Django 5.1.6 on 2025-03-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0007_transferencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferencia",
            name="correo_cliente",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transferencia",
            name="nombre_cliente",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transferencia",
            name="telefono_cliente",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
    ]
