# Generated by Django 5.1.6 on 2025-03-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0008_transferencia_correo_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferencia",
            name="tipo_cuenta",
            field=models.CharField(
                choices=[
                    ("CORRIENTE", "Cuenta Corriente"),
                    ("AHORROS", "Cuenta de Ahorros"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
